id: A7E861421
title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku of Jamyang
  Khyentse, Thupten Chökyi Gyatso'
type: translation
pechas:
- I1F268888
- ID9435989
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:05.260769
  last_modified_at: 2023-01-04 11:51:05.260785
  collections:
  - Dzongsar Khyentse Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I1F268888/0339: 55B9
  ID9435989/6AD9: 55B9
